plugin/admin/admin-pages/advanced/lightbox.php, plugin/class-options.php, plugin/frontend/class-options-proxy.php, plugin/frontend/js/shortcode.js, plugin/frontend/page.php, plugin/frontend/shortcode.php, plugin/uninstall.php
Implementation of feature from issue https://github.com/skaut/skaut-google-drive-gallery/issues/68. I am not a Wordpress plugin, PHP or JS programmer, so please check the code carefully :).  I think we should probably sanitize the caption string somehow, but I don't know what is the usual way to do it in PHP. (It is probably sanitized already on the gdrive, but who knows...).
BTW 1: I haven't found where to put czech localization of the config option.
=> Add option to show image description / title

.circleci/config.yml, gulpfile.js
CI now checks whether updated dependencies need to be copied over.
=> Dependency synchronization checking

.circleci/config.yml, gulpfile.js
=> WIP: Making phan run in CI

composer.json, plugin/readme.txt
=> Renamed the plugin

plugin/frontend/js/shortcode.js
=> Fixed error when JS would break on missing AJAX response fields

src/php/frontend/shortcode.php
=> Handling Google errors in shortcode rendering

src/css/admin/tinymce.css, src/js/admin/tinymce.js
=> Fixed TinyMCE table overflowing the thickbox

src/js/admin/root_selection.js, src/php/admin/admin-pages/basic/root-selection.php
=> Fixed invalid path in root selector handling

src/js/admin/tinymce.js, src/js/frontend/SgdgEditorComponent.js
=> Fixed issue with & in folder name

src/php/frontend/page.php
=> Removed TODOs

src/ts/frontend/shortcode/Shortcode.ts
=> Fixed missing space in breadcrumbs

gulpfile.js, src/php/admin/admin-pages/basic/root-selection.php, src/php/admin/tinymce.php, src/php/bundled/vendor-includes.php, src/php/frontend/page.php, src/php/frontend/shortcode.php
=> Google Drive shortcut support

.github/workflows/CI.yml
This reverts commit b0ea77dae1727883cfb3c3d02f7ff06a17bd83d0 and PR #671.
=> Revert "CI fix"

src/ts/frontend/block.ts
=> Gutenberg block in media category

package-lock.json, package.json
Changed the branch use a bit on the forked repo. Nothing of substance changes.
=> Switched justified-layout to skaut/justified-layout#master

src/php/frontend/page.php
Returned directories weren't re-indexed if some were removed.
Closes #759
=> Fixed galleries being incorrectly reported as empty

composer.lock
Changed the composer lockfile for composer 2.0
=> Composer 2.0

package-lock.json, package.json, src/css/admin/options-root.css, src/php/admin/admin-pages/basic/root-selection.php, src/ts/admin/root_selection.ts
=> Re-enabled stylelint

package-lock.json
=> Fixed breaking change in browserify config

composer.lock, package-lock.json, package.json, src/php/skaut-google-drive-gallery.php, src/txt/readme.txt
=> Version 2.10.4

bin/install-wp-tests.sh, composer.json, composer.lock, phpunit.xml, tests/bootstrap.php
See https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/
=> Unit testing infrastructure upgrade

scoper.inc.php
=> Fixed a minor collision in the autoloader

composer.json, composer.lock
=> Switched to paragonie/constant_time_encoding v1.1.0

src/ts/frontend/shortcode/Shortcode.ts
=> Fixed a bug where pages would get added to the gallery infinitely

.snyk
=> Removed snyk config

src/txt/readme.txt
=> Bumped tested-up-to to WordPress 6

composer.json, composer.lock, src/php/helpers/class-get-helpers.php, src/ts/frontend/block.ts
=> Fixed galleries with leading or trailing spaces in names

scoper.inc.php
=> Automatic composer dependency bundling

.github/workflows/CI.yml
=> Using codecov/codecov-action

.github/workflows/CI.yml, .github/workflows/release.yml
=> Switched back to upstream node

composer.json, composer.lock
This reverts commit 312808813bbc12e2e50997bf36d34070ee694e81.
=> Revert "Build(deps): Bump guzzlehttp/promises from 1.5.0 to 1.5.2"

composer.lock, package-lock.json, package.json, src/php/skaut-google-drive-gallery.php, src/txt/readme.txt
- Composer update
- NPM update
- Version 2.13.2
=> Version 2.13.2

src/php/admin/settings-pages/basic/root-selection/class-list-ajax-endpoint.php, src/php/class-api-client.php, src/php/class-api-facade.php
=> Fixed an error with empty batch request when trying to select root folder from a list of drives

src/ts/frontend/block/SgdgOrderingSettingsComponent.ts, src/ts/frontend/block/SgdgSettingsComponent.ts
=> Fixed block settings override labels

phpcs.xml, src/php/frontend/page/class-videos.php
=> Fixed error on unshared video

src/php/class-api-client.php
=> Setting the Drive client to always use batching

src/php/admin/settings-pages/basic/root-selection/class-list-ajax-endpoint.php, src/php/frontend/class-gallery.php, src/php/frontend/class-page.php
=> Not using wp_send_json in promises

src/php/class-api-facade.php, src/php/frontend/class-api-fields.php
- Fixed mime type checking for shortcuts
- Fixed checking a directory is in directory to work with shortcuts
Fixes #2511
=> Fixed handling of shortcuts

src/txt/readme.txt
=> Limited tags to 5 entries

.github/workflows/release.yml
- **Not using ::set-output**
- **Using softprops/action-gh-release**
=> Updated release action to not use deprecated features

.github/workflows/CI.yml, .github/workflows/release.yml
- **Renamed release job**
- **Using default NodeJS version in actions**
- **Composer prefering dist**
=> Random actions upgrades

.github/workflows/asset-update.yml, .github/workflows/release.yml
=> Automatic wordpress.org deploy
